[package]
name = "avelonia"
version = "0.1.0"
description = "A Tauri App"
authors = ["Evoq", "Pysen"]
edition = "2021"

[lib]
name = "avelonia_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
sha2 = "^0.10"
trash = "^5"
windows = { version = "^0.61", features = ["Win32_UI_Shell", "Win32_Foundation"] }
sysinfo = "0.37"
lnk = "^0.6"
reqwest = { version = "0.12", features = ["stream"] }
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
dashmap = "5.5.3"
rand = "0.8"
winreg = "0.52"
csv = "1"
