import type { Download } from './downloadManager';

export const COMMUNICATION_DOWNLOADS: Download[] = [
  {
    id: 1,
    name: 'Discord',
    description: 'Voice & chat client for communities',
    size: '105 MB',
    fileType: 'exe',
    category: 'Communication',
    tags: ['Chat', 'Community'],
    downloadLink: 'https://discord.com/api/download?platform=win',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 2,
    name: 'WhatsApp Desktop',
    description: 'Desktop client for WhatsApp messaging',
    size: '160 MB',
    fileType: 'exe',
    category: 'Communication',
    tags: ['Chat', 'Messaging'],
    downloadLink: 'https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 3,
    name: 'Slack',
    description: 'Team messaging app',
    size: '160 MB',
    fileType: 'exe',
    category: 'Collaboration',
    tags: ['Chat', 'Productivity'],
    downloadLink:
      'https://downloads.slack-edge.com/releases/windows/5.37.150/prod/x64/SlackSetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 52,
    name: 'Element',
    description: 'Matrix-based secure chat with bridging to other networks',
    size: '220 MB',
    fileType: 'exe',
    category: 'Communication',
    tags: ['Chat', 'Privacy'],
    downloadLink: 'https://packages.element.io/desktop/install/win32/x64/Element%20Setup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 4,
    name: 'Microsoft Teams',
    description: 'Collaboration hub for chat, meetings, and files',
    size: '170 MB',
    fileType: 'exe',
    category: 'Collaboration',
    tags: ['Meetings', 'Productivity'],
    downloadLink: 'https://aka.ms/teamsdownload?env=production&plat=win64',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 5,
    name: 'Zoom',
    description: 'Video conferencing client',
    size: '90 MB',
    fileType: 'exe',
    category: 'Collaboration',
    tags: ['Video', 'Meetings'],
    downloadLink: 'https://zoom.us/client/latest/ZoomInstaller.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 6,
    name: 'Signal Desktop',
    description: 'Encrypted messaging with voice and video',
    size: '150 MB',
    fileType: 'exe',
    category: 'Security',
    tags: ['Chat', 'Privacy'],
    downloadLink: 'https://updates.signal.org/desktop/signal-desktop-win-Setup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 7,
    name: 'Telegram Desktop',
    description: 'Cross-platform messaging with cloud storage',
    size: '90 MB',
    fileType: 'exe',
    category: 'Communication',
    tags: ['Chat', 'Cloud'],
    downloadLink: 'https://telegram.org/dl/desktop/win64',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 61,
    name: 'SimpleX Desktop',
    description: 'Secure chat built on the SimpleX protocol with decentralized messaging',
    size: '180 MB',
    fileType: 'msi',
    category: 'Communication',
    tags: ['Chat', 'Privacy', 'Decentralized'],
    downloadLink:
      'https://github.com/simplex-chat/simplex/releases/latest/download/simplex-desktop-windows-x86_64.msi',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
];

export const BROWSERS_DOWNLOADS: Download[] = [
  {
    id: 8,
    name: 'Google Chrome',
    description: 'Chromium-based browser with sync and extension support',
    size: '120 MB',
    fileType: 'exe',
    category: 'Web',
    tags: ['Browser', 'Productivity'],
    downloadLink: 'https://dl.google.com/chrome/install/latest/chrome_installer.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 9,
    name: 'Mozilla Firefox',
    description: 'Privacy-focused browser with strong security controls',
    size: '110 MB',
    fileType: 'exe',
    category: 'Web',
    tags: ['Browser', 'Security'],
    downloadLink: 'https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 10,
    name: 'Microsoft Edge',
    description: 'Microsoft-built Chromium browser with collections and enterprise support',
    size: '150 MB',
    fileType: 'exe',
    category: 'Web',
    tags: ['Browser', 'Enterprise'],
    downloadLink: 'https://go.microsoft.com/fwlink/?linkid=2069148',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 11,
    name: 'Brave Browser',
    description: 'Privacy-first browser with built-in ad blocking',
    size: '115 MB',
    fileType: 'exe',
    category: 'Web',
    tags: ['Browser', 'Privacy'],
    downloadLink: 'https://laptop-updates.brave.com/latest/winx64',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 12,
    name: 'Vivaldi',
    description: 'Highly customizable Chromium browser with built-in sidebar tools',
    size: '120 MB',
    fileType: 'exe',
    category: 'Web',
    tags: ['Browser', 'Customization'],
    downloadLink: 'https://downloads.vivaldi.com/stable/VivaldiSetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 13,
    name: 'Arc Browser',
    description: 'Innovative browser focused on productivity and built-in workspaces',
    size: '250 MB',
    fileType: 'exe',
    category: 'Web',
    tags: ['Browser', 'Productivity'],
    downloadLink: 'https://arc.net/download/windows',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 49,
    name: 'Tor Browser',
    description: 'Privacy-first browser that routes traffic through the Tor network',
    size: '100 MB',
    fileType: 'exe',
    category: 'Web',
    tags: ['Privacy', 'Security'],
    downloadLink: 'https://www.torproject.org/dist/torbrowser/latest/torbrowser-install-win64.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
];

export const PRODUCTIVITY_DOWNLOADS: Download[] = [
  {
    id: 14,
    name: 'Notion',
    description: 'All-in-one workspace for notes, docs, and tasks',
    size: '210 MB',
    fileType: 'exe',
    category: 'Productivity',
    tags: ['Notes', 'Teamwork'],
    downloadLink: 'https://www.notion.so/desktop/NotionSetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 15,
    name: 'Figma',
    description: 'Collaborative interface design tool',
    size: '200 MB',
    fileType: 'exe',
    category: 'Design',
    tags: ['Design', 'Collaboration'],
    downloadLink: 'https://desktop.figma.com/win/FigmaSetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 16,
    name: 'GIMP',
    description: 'Open-source image editor',
    size: '210 MB',
    fileType: 'exe',
    category: 'Design',
    tags: ['Graphics', 'Creative'],
    downloadLink: 'https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.38-setup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 17,
    name: 'LibreOffice',
    description: 'Full-featured office suite',
    size: '310 MB',
    fileType: 'msi',
    category: 'Productivity',
    tags: ['Office', 'Suite'],
    downloadLink:
      'https://download.documentfoundation.org/libreoffice/stable/7.6.6/win/x86_64/LibreOffice_7.6.6_Win_x64.msi',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 18,
    name: 'Google Drive for Desktop',
    description: 'Sync and backup files to Google Drive',
    size: '70 MB',
    fileType: 'exe',
    category: 'Productivity',
    tags: ['Cloud', 'Sync'],
    downloadLink: 'https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 19,
    name: 'Dropbox Desktop',
    description: 'File sync and sharing platform',
    size: '30 MB',
    fileType: 'exe',
    category: 'Productivity',
    tags: ['Cloud', 'Sync'],
    downloadLink: 'https://www.dropbox.com/download?plat=win',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 20,
    name: 'Adobe Acrobat Reader',
    description: 'PDF reader with commenting tools',
    size: '220 MB',
    fileType: 'exe',
    category: 'Productivity',
    tags: ['PDF', 'Tools'],
    downloadLink:
      'https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2401020040/AcroRdrDC2401020040_en_US.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 21,
    name: 'Microsoft PowerToys',
    description: 'Productivity utilities for power users',
    size: '58 MB',
    fileType: 'exe',
    category: 'Productivity',
    tags: ['Utilities', 'Tools'],
    downloadLink:
      'https://github.com/microsoft/PowerToys/releases/latest/download/PowerToysSetup-x64.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 41,
    name: 'Obsidian',
    description: 'Markdown-based knowledge base with backlinking',
    size: '155 MB',
    fileType: 'exe',
    category: 'Productivity',
    tags: ['Notes', 'Knowledge', 'Markdown'],
    downloadLink: 'https://obsidian.md/download?platform=win',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 69,
    name: 'Windows Terminal',
    description: 'Modern terminal with tabs, panes, and GPU-accelerated text rendering',
    size: '30 MB',
    fileType: 'msixbundle',
    category: 'Productivity',
    tags: ['Terminal', 'Shell'],
    downloadLink: 'https://aka.ms/terminal',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 42,
    name: 'Todoist Desktop',
    description: 'Task manager with boards, reminders, and productivity views',
    size: '50 MB',
    fileType: 'exe',
    category: 'Productivity',
    tags: ['Tasks', 'Planning'],
    downloadLink: 'https://download.todoist.com/windows/TodoistSetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 62,
    name: 'Cursor',
    description: 'AI-powered coding assistant with IDE-style workflows',
    size: '150 MB',
    fileType: 'zip',
    category: 'Productivity',
    tags: ['AI', 'Coding'],
    downloadLink: 'https://api2.cursor.sh/updates/download/golden/win32-x64/cursor/2.0',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 63,
    name: 'Windsurf',
    description: 'AI-companion for product teams with collaborative workspaces',
    size: '180 MB',
    fileType: 'exe',
    category: 'Productivity',
    tags: ['AI', 'Collaboration'],
    downloadLink: 'https://windsurf.com/download',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
];

export const DEVELOPMENT_DOWNLOADS: Download[] = [
  {
    id: 22,
    name: 'Visual Studio Code',
    description: 'Lightweight code editor',
    size: '120 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['Editor', 'IDE'],
    downloadLink: 'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user',
    releases: [
      {
        label: 'Stable',
        downloadLink: 'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user',
        size: '120 MB',
        fileType: 'exe',
      },
      {
        label: 'Insiders',
        downloadLink: 'https://update.code.visualstudio.com/latest/win32-x64-user-insider/stable',
        size: '124 MB',
        fileType: 'exe',
      },
    ],
    selectedReleaseLabel: 'Stable',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 23,
    name: 'GitHub Desktop',
    description: 'Git client with a friendly GUI',
    size: '100 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['Git', 'Collaboration'],
    downloadLink: 'https://central.github.com/deployments/desktop/desktop/latest/win64',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 25,
    name: 'Python',
    description: 'General-purpose programming language runtime',
    size: '26 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['Runtime', 'Tools'],
    downloadLink: 'https://www.python.org/ftp/python/3.12.3/python-3.12.3-amd64.exe',
    releases: [
      {
        label: '3.12.3 (Latest)',
        downloadLink: 'https://www.python.org/ftp/python/3.12.3/python-3.12.3-amd64.exe',
        size: '26 MB',
        fileType: 'exe',
      },
      {
        label: '3.11.6 (LTS)',
        downloadLink: 'https://www.python.org/ftp/python/3.11.6/python-3.11.6-amd64.exe',
        size: '25 MB',
        fileType: 'exe',
      },
      {
        label: '3.10.12 (Legacy)',
        downloadLink: 'https://www.python.org/ftp/python/3.10.12/python-3.10.12-amd64.exe',
        size: '25 MB',
        fileType: 'exe',
      },
    ],
    selectedReleaseLabel: '3.12.3 (Latest)',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 26,
    name: 'Node.js',
    description: 'JavaScript runtime for servers and tools',
    size: '35 MB',
    fileType: 'msi',
    category: 'Development',
    tags: ['Runtime', 'JavaScript'],
    downloadLink: 'https://nodejs.org/dist/v22.5.0/node-v22.5.0-x64.msi',
    releases: [
      {
        label: 'LTS (v22.5.0)',
        downloadLink: 'https://nodejs.org/dist/v22.5.0/node-v22.5.0-x64.msi',
        size: '35 MB',
        fileType: 'msi',
      },
      {
        label: 'Current (v23.1.0)',
        downloadLink: 'https://nodejs.org/dist/v23.1.0/node-v23.1.0-x64.msi',
        size: '36 MB',
        fileType: 'msi',
      },
    ],
    selectedReleaseLabel: 'LTS (v22.5.0)',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 64,
    name: 'GitHub CLI',
    description: 'Command-line tool for interacting with GitHub from scripts and shells',
    size: '24 MB',
    fileType: 'msi',
    category: 'Development',
    tags: ['Git', 'CLI'],
    downloadLink: 'https://github.com/cli/cli/releases/latest/download/gh-windows-amd64.msi',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 65,
    name: 'Git for Windows',
    description: 'Distributed version control with Git Bash and native tooling',
    size: '50 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['Git', 'Version Control'],
    downloadLink: 'https://github.com/git-for-windows/git/releases/latest/download/Git-64-bit.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 59,
    name: 'Bun',
    description: 'All-in-one JavaScript runtime, bundler, and package manager',
    size: '70 MB',
    fileType: 'zip',
    category: 'Development',
    tags: ['Runtime', 'Tools'],
    downloadLink: 'https://github.com/oven-sh/bun/releases/latest/download/bun-windows-x64.zip',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 60,
    name: 'Java (Oracle JDK)',
    description: 'Industry-leading JDK with long-term support releases',
    size: '220 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['Language', 'Runtime'],
    downloadLink: 'https://download.oracle.com/java/23/latest/jdk-23_windows-x64_bin.exe',
    releases: [
      {
        label: 'Java 23 (Current)',
        downloadLink: 'https://download.oracle.com/java/23/latest/jdk-23_windows-x64_bin.exe',
        size: '220 MB',
        fileType: 'exe',
      },
      {
        label: 'Java 17 (LTS)',
        downloadLink: 'https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe',
        size: '210 MB',
        fileType: 'exe',
      },
    ],
    selectedReleaseLabel: 'Java 23 (Current)',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 50,
    name: 'Go',
    description: 'Statically typed compiled language with fast builds',
    size: '150 MB',
    fileType: 'msi',
    category: 'Development',
    tags: ['Language', 'Tools'],
    downloadLink: 'https://go.dev/dl/go1.22.5.windows-amd64.msi',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 51,
    name: 'Rust (Rustup)',
    description: 'Installer for the Rust toolchain and cargo package manager',
    size: '3.5 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['Language', 'Tools'],
    downloadLink: 'https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 43,
    name: 'Postman',
    description: 'API development environment for building and testing',
    size: '220 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['API', 'Tools'],
    downloadLink: 'https://dl.pstmn.io/download/latest/win64',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 44,
    name: 'JetBrains Toolbox',
    description: 'Centralized installer and updater for JetBrains IDEs',
    size: '40 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['IDE', 'Tools'],
    downloadLink: 'https://data.services.jetbrains.com/products/download?code=TB&platform=Windows',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 70,
    name: 'Docker Desktop',
    description:
      'Container management for building and running Docker images with Kubernetes support',
    size: '650 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['Containers', 'DevOps'],
    downloadLink: 'https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 71,
    name: 'Syncthing',
    description: 'Private continuous file synchronization across devices',
    size: '40 MB',
    fileType: 'exe',
    category: 'Development',
    tags: ['Sync', 'Utility'],
    downloadLink:
      'https://github.com/syncthing/syncthing/releases/latest/download/syncthing-windows-amd64.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
];

export const GAMING_DOWNLOADS: Download[] = [
  {
    id: 27,
    name: 'Steam',
    description: 'Gaming platform with a massive catalog of titles',
    size: '70 MB',
    fileType: 'exe',
    category: 'Gaming',
    tags: ['Games', 'Launcher'],
    downloadLink: 'https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 28,
    name: 'Epic Games Launcher',
    description: 'Launcher for games distributed through Epic Games Store',
    size: '135 MB',
    fileType: 'msi',
    category: 'Gaming',
    tags: ['Games', 'Launcher'],
    downloadLink:
      'https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 29,
    name: 'Battle.net Desktop App',
    description: 'Blizzard’s launcher for PC games and updates',
    size: '60 MB',
    fileType: 'exe',
    category: 'Gaming',
    tags: ['Games', 'Launcher'],
    downloadLink: 'https://www.blizzard.com/en-us/download/BlizzardAppInstaller.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 30,
    name: 'OBS Studio',
    description: 'Open-source video recording and live streaming tool',
    size: '90 MB',
    fileType: 'exe',
    category: 'Media',
    tags: ['Streaming', 'Recording'],
    downloadLink:
      'https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.2.1-Full-Installer-x64.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 31,
    name: 'VLC Media Player',
    description: 'Open-source media player that handles nearly any format',
    size: '45 MB',
    fileType: 'exe',
    category: 'Media',
    tags: ['Video', 'Audio'],
    downloadLink: 'https://get.videolan.org/vlc/3.0.20/win64/vlc-3.0.20-win64.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 53,
    name: 'Spotify',
    description: 'Stream music and podcasts across devices',
    size: '60 MB',
    fileType: 'exe',
    category: 'Media',
    tags: ['Audio', 'Streaming'],
    downloadLink: 'https://download.scdn.co/SpotifySetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 54,
    name: 'Ubisoft Connect',
    description: 'Launcher for Ubisoft games, social features, and rewards',
    size: '120 MB',
    fileType: 'exe',
    category: 'Gaming',
    tags: ['Games', 'Launcher'],
    downloadLink: 'https://ubisoftconnect.com/download?platform=windows',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 45,
    name: 'GOG Galaxy',
    description: 'Gaming client with DRM-free catalog and friends lists',
    size: '90 MB',
    fileType: 'exe',
    category: 'Gaming',
    tags: ['Games', 'Launcher'],
    downloadLink: 'https://static.gog.com/download/GOG_Galaxy_2.0.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 46,
    name: 'Audacity',
    description: 'Open-source audio editor for recording and editing',
    size: '35 MB',
    fileType: 'exe',
    category: 'Media',
    tags: ['Audio', 'Recording'],
    downloadLink: 'https://www.fosshub.com/Audacity.html?dwl=audacity-win-3.4.2-x64.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
];

export const SYSTEM_DOWNLOADS: Download[] = [
  {
    id: 32,
    name: 'NVIDIA App (GeForce Experience)',
    description:
      'Unified driver updates, recording, and capture experience for GeForce GPUs (formerly GeForce Experience)',
    size: '165 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Drivers', 'Gaming'],
    downloadLink:
      'https://us.download.nvidia.com/Windows/536.67/536.67-desktop-win10-win11-64bit-international-whql.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 33,
    name: 'AMD Radeon Software',
    description: 'Driver updates for Radeon GPUs with performance tuning',
    size: '120 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Drivers', 'Gaming'],
    downloadLink:
      'https://drivers.amd.com/drivers/installer/AMD-Radeon-Software-Adrenalin-24.20.2-Installer.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 34,
    name: 'Intel Driver & Support Assistant',
    description: 'Keeps Intel components up to date with automated scans',
    size: '5.3 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Drivers', 'Utility'],
    downloadLink: 'https://downloadmirror.intel.com/31824/a08/dsa_appsetup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 35,
    name: 'Microsoft Visual C++ Redistributable 2022',
    description: 'Required runtime for many Windows applications',
    size: '20 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Runtime', 'System'],
    downloadLink: 'https://aka.ms/vs/17/release/vc_redist.x64.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 36,
    name: '.NET Runtime',
    description: 'Modern .NET runtime for desktop and web apps',
    size: '46 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Runtime', 'Sdk'],
    downloadLink:
      'https://dotnetcli.azureedge.net/dotnet/Runtime/9.0.0/dotnet-runtime-9.0.0-win-x64.exe',
    releases: [
      {
        label: '.NET 9.0 (Current)',
        downloadLink:
          'https://dotnetcli.azureedge.net/dotnet/Runtime/9.0.0/dotnet-runtime-9.0.0-win-x64.exe',
        size: '46 MB',
        fileType: 'exe',
      },
      {
        label: '.NET 8.0 (Latest LTS)',
        downloadLink:
          'https://download.visualstudio.microsoft.com/download/pr/4c9c25d7-63e3-403c-b51c-77c52c2d7144/b27d3b4576604305e1ae6f7262f0a262/dotnet-runtime-8.0.0-win-x64.exe',
        size: '45 MB',
        fileType: 'exe',
      },
      {
        label: '.NET 7.0 (LTS)',
        downloadLink:
          'https://download.visualstudio.microsoft.com/download/pr/a0d5aa5a-4da4-4f53-8ea5-0a481530cd64/9344c127d06c7962d1b4fc8d1efc9f59/dotnet-runtime-7.0.12-win-x64.exe',
        size: '55 MB',
        fileType: 'exe',
      },
    ],
    selectedReleaseLabel: '.NET 9.0 (Current)',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 37,
    name: 'DirectX End-User Runtime Web Installer',
    description: 'Legacy DirectX components needed by many games',
    size: '2 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Gaming', 'Compatibility'],
    downloadLink: 'https://go.microsoft.com/fwlink/?LinkId=35',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 38,
    name: '7-Zip',
    description: 'Lightweight file archiver with high compression ratio',
    size: '1.2 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Compression', 'Tools'],
    downloadLink: 'https://www.7-zip.org/a/7z2301-x64.exe',
    hash: '094f794356e99e09968412854964177d704285e6edc6533c3919e18e807353f2',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 39,
    name: 'WinRAR',
    description: 'Compression utility that opens RAR archives',
    size: '4 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Compression', 'Tools'],
    downloadLink: 'https://www.rarlab.com/rar/winrar-x64-611.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 40,
    name: 'Malwarebytes',
    description: 'Anti-malware that works alongside Windows Defender',
    size: '80 MB',
    fileType: 'exe',
    category: 'Security',
    tags: ['Security', 'Tools'],
    downloadLink: 'https://downloads.malwarebytes.com/file/mb3',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 55,
    name: 'Mullvad VPN',
    description: 'No-logs VPN with WireGuard support and strong privacy defaults',
    size: '90 MB',
    fileType: 'exe',
    category: 'Security',
    tags: ['VPN', 'Privacy'],
    downloadLink: 'https://mullvad.net/download/app/windows/latest',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 56,
    name: 'Proton VPN',
    description: 'Privacy-first VPN from the ProtonMail team',
    size: '80 MB',
    fileType: 'exe',
    category: 'Security',
    tags: ['VPN', 'Privacy'],
    downloadLink: 'https://protonvpn.com/download/ProtonVPN.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 66,
    name: 'MetaMask Desktop',
    description: 'Desktop wallet for Ethereum and Web3 dapps',
    size: '130 MB',
    fileType: 'exe',
    category: 'Security',
    tags: ['Crypto', 'Wallet'],
    downloadLink:
      'https://github.com/MetaMask/metamask-desktop/releases/latest/download/MetaMask-Setup.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 67,
    name: 'Ledger Live',
    description: 'Ledger hardware wallet companion for managing crypto portfolios',
    size: '200 MB',
    fileType: 'exe',
    category: 'Security',
    tags: ['Crypto', 'Hardware'],
    downloadLink: 'https://download.live.ledger.com/latest/win/ledger-live-desktop.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 68,
    name: 'Exodus',
    description: 'Multi-asset crypto wallet with a built-in exchange',
    size: '120 MB',
    fileType: 'exe',
    category: 'Security',
    tags: ['Crypto', 'Wallet'],
    downloadLink: 'https://www.exodus.com/download/',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 57,
    name: 'Everything (voidtools)',
    description: 'Instant file and folder search for Windows',
    size: '8.8 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Search', 'Tools'],
    downloadLink: 'https://www.voidtools.com/Everything-1.4.1.1075.x64-Setup.exe',
    hash: '0000000000000000000000000000000000000000000000000000000000000000',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 58,
    name: 'Logitech G HUB',
    description: 'Peripheral software for Logitech gaming mice, keyboards, and headsets',
    size: '220 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['Drivers', 'Peripheral'],
    downloadLink:
      'https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub/LGHUB_3.0.127_2.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 47,
    name: 'Rufus',
    description: 'Create bootable USB drives quickly',
    size: '2.5 MB',
    fileType: 'exe',
    category: 'System',
    tags: ['USB', 'Boot'],
    downloadLink: 'https://github.com/pbatard/rufus/releases/download/v4.0/rufus-4.0.exe',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
  {
    id: 48,
    name: 'KeePassXC',
    description: 'Cross-platform password manager with strong encryption',
    size: '32 MB',
    fileType: 'msi',
    category: 'Security',
    tags: ['Passwords', 'Security'],
    downloadLink:
      'https://github.com/keepassxreboot/keepassxc/releases/download/2.7.1/KeePassXC-2.7.1-Win64.msi',
    eta: 'N/A',
    status: 'available',
    progress: 0,
  },
];

export const BUILT_IN_DOWNLOAD_GROUPS = [
  {
    title: 'Communication & Collaboration',
    downloads: COMMUNICATION_DOWNLOADS,
  },
  {
    title: 'Web & Browsers',
    downloads: BROWSERS_DOWNLOADS,
  },
  {
    title: 'Productivity & Utilities',
    downloads: PRODUCTIVITY_DOWNLOADS,
  },
  {
    title: 'Development & Tools',
    downloads: DEVELOPMENT_DOWNLOADS,
  },
  {
    title: 'Gaming & Media',
    downloads: GAMING_DOWNLOADS,
  },
  {
    title: 'System & Drivers',
    downloads: SYSTEM_DOWNLOADS,
  },
];
