export const programs = [
  {
    id: 101,
    name: 'Google Chrome',
    description: 'A fast, secure, and free web browser built for the modern web.',
    size: '120 MB',
    fileType: 'exe',
    category: 'Browser',
    downloadLink: 'https://dl.google.com/chrome/installer/stable/chrome_installer.exe',
  },
  {
    id: 102,
    name: 'Mozilla Firefox',
    description: 'A free and open-source web browser developed by the Mozilla Foundation.',
    size: '55 MB',
    fileType: 'exe',
    category: 'Browser',
    downloadLink: 'https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US',
  },
  {
    id: 103,
    name: 'VLC Media Player',
    description: 'A free and open-source portable cross-platform media player software.',
    size: '43 MB',
    fileType: 'exe',
    category: 'Multimedia',
    downloadLink: 'https://get.videolan.org/vlc/3.0.21/win64/vlc-3.0.21-win64.exe',
  },
  {
    id: 104,
    name: '7-Zip',
    description: 'A free and open-source file archiver with a high compression ratio.',
    size: '1.6 MB',
    fileType: 'exe',
    category: 'Utility',
    downloadLink: 'https://www.7-zip.org/a/7z2501-x64.exe',
  },
  {
    id: 105,
    name: 'Discord',
    description: 'Free voice, video, and text chat for your communities.',
    size: '90 MB',
    fileType: 'exe',
    category: 'Communication',
    downloadLink: 'https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86',
  },
];
