export const programs = [
  {
    id: 101,
    name: 'Google Chrome',
    description: 'A fast, secure, and free web browser built for the modern web.',
    size: '120 MB',
    fileType: 'exe',
    category: 'Browser',
    downloadLink: 'https://example.com/chrome_installer.exe',
  },
  {
    id: 102,
    name: 'Mozilla Firefox',
    description: 'A free and open-source web browser developed by the Mozilla Foundation.',
    size: '100 MB',
    fileType: 'exe',
    category: 'Browser',
    downloadLink: 'https://example.com/firefox_installer.exe',
  },
  {
    id: 103,
    name: 'VLC Media Player',
    description: 'A free and open-source portable cross-platform media player software.',
    size: '40 MB',
    fileType: 'exe',
    category: 'Multimedia',
    downloadLink: 'https://example.com/vlc_installer.exe',
  },
  {
    id: 104,
    name: '7-Zip',
    description: 'A free and open-source file archiver with a high compression ratio.',
    size: '5 MB',
    fileType: 'exe',
    category: 'Utility',
    downloadLink: 'https://example.com/7zip_installer.exe',
  },
  {
    id: 105,
    name: 'Discord',
    description: 'Free voice, video, and text chat for your communities.',
    size: '80 MB',
    fileType: 'exe',
    category: 'Communication',
    downloadLink: 'https://example.com/discord_installer.exe',
  },
];
